In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable


DEPRECATION: Loading egg at c:\programdata\anaconda3\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..


In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.24.4


## 1. creating arrays

## 1d array

In [5]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [7]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [8]:
print(type(arr_list1))

<class 'numpy.ndarray'>


## 2d array

In [11]:
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1_2 = np.array([list1, list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


## 3d array

In [14]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,7,9]
arr_list1_3=np.array([list1, list2, list3])
print(arr_list1_3)

[[1 2 3]
 [4 5 6]
 [7 7 9]]


In [15]:
print(arr_list1_3.ndim)

2


In [16]:
print(arr_list1.ndim)

1


In [21]:
print(arr_list1_2.ndim)

2


In [22]:
print(arr_list1_3.ndim)

2


# # 2. numpy array attributes

In [23]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [24]:
print("Shape", arr1.shape)
print("Size", arr1.size)
print("dtype",arr1.dtype)
print("n_dim", arr1.ndim)

Shape (2, 3)
Size 6
dtype int32
n_dim 2


## 3. Array Initilization methods

In [26]:
# Zero array
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
# one array
one_arr = np.ones((1,3))
print(one_arr)

[[1. 1. 1.]]


In [30]:
# Full array
full_arr = np.full((3,2), 7)
print(full_arr)


[[7 7]
 [7 7]
 [7 7]]


In [4]:
# Identity matrix
import numpy as np
int_eye = np.eye(3, dtype=int)
print(int_eye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
# Empty array
print(np.empty(2))

[-6.42447058e-027 -2.48834108e+307]


In [9]:
# empty spaced array
print(np.arange(2,10,2))

[2 4 6 8]


In [11]:
# Specific values between a range (equally spaced)
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [12]:
# random values array - float
r_arr = np.random.rand(3,2)
print(r_arr)

[[0.49561363 0.73944611]
 [0.77521076 0.16646004]
 [0.6326798  0.60070364]]


In [16]:
# random values array -int
rint_arr = np.random.randint(1,100,(3,4))
print(rint_arr)

[[83 12 52 53]
 [49 44 20 19]
 [29 58 49 89]]


## 4. Array indexing and slicing

In [17]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [20]:
print(a[4])

9


In [22]:
print(a[-3])

5


In [24]:
# Slicing
#array[start:stop:step]

In [26]:
print(a[0:2]) # first two elements

[1 3]


In [29]:
print(a[-3]) # last 3 elements

5


In [30]:
print(a[0:4:1]) # middle 3 elements

[1 3 5 7]


In [31]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [34]:
print(arr2[0][1])

2


In [35]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [44]:
arr3 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [46]:
print(arr3[0][2])
print(arr3[2][2])

3
9


In [48]:
print(arr3[:,2]) #1st col value
print(arr3[2][2]) #2nd col value

[3 6 9]
9


In [50]:
print(arr3[::, 1:2]) #slicing on columns
print(arr3[2::, 1:2]) # slicing on row columns

[[2]
 [5]
 [8]]
[[8]]


## 5. Array Reshaping and Flattening

In [56]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)

print("Original Array:")
print(arr)

print("\nReshaped Array:")
print(reshaped)

Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


In [57]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

flat = arr.flatten()

print("Original Array:")
print(arr)

print("\nFlattened Array:")
print(flat)

Original Array:
[[10 20 30]
 [40 50 60]]

Flattened Array:
[10 20 30 40 50 60]


## 6. Array Stacking and Splitting

In [62]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b))) # vertical stacking - row wise

print(np.stack((a,b))) # horizontal stacking - column wise

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [65]:
c = np.array([[1,2,3], [4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


split = np.hsplit(c,3) # horizontal split
for s in split:
    print(s)

In [70]:
split = np.vsplit(c,2) # vertical split
for s in split:
    print(s)

[[1 2 3]]
[[4 5 6]]


## 7 Mathematical operations on Array

In [72]:
a = np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]


In [73]:
print(a+10)
print(a-30)
print(a*2)
print(a/10)

[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]


In [74]:
b = np.array([1,4,9])
print(b)

[1 4 9]


In [75]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


## 8 Mathematical operations on Multiple Arrays

In [76]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [78]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [79]:
print(np.dot(a,b)) # dot product

32


In [80]:
print(a.T) # Transpose

[1 2 3]


In [82]:
t = np.array([[1,2,3],
             [4,5,6]])
print(t)
print(t.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## 9 Stastical operations

In [84]:
a = np.array([[1,2,3], [4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [85]:
print(a.sum())

21


In [86]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))


3.5
3.5
1.707825127659933
1
6


## 10 Array Comparision

In [88]:
a = np.array([25,35,49,97])
b = np.array([4,5,6])
print(a)
print(b)

[25 35 49 97]
[4 5 6]


In [90]:
print(a == b) # comparing each element
print(np.array_equal(a,b)) # comparing complete array



False
False


C:\Users\Subhashini\AppData\Local\Temp\ipykernel_11120\3500817139.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(a == b) # comparing each element


## 11 Broadacasting

In [93]:
a = np.array([1,2,3,4])
b = np.array([5])
print(a+b)

[6 7 8 9]


In [94]:
c = np.array([[1,2,3], [4,5,6]])
d = np.array([10,20,30])
print(c+d)

[[11 22 33]
 [14 25 36]]


## 12 Handling With nan

In [95]:
data1 = np.array([1,2, np.nan, 4, np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [96]:
print(np.isnan(data1))

[False False  True False False]


In [97]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [98]:
# save and load arrays

In [99]:
arr = np.array([1,0,0,8])
print(arr)
np.save('my_array.npy',arr)

[1 0 0 8]


In [1]:
import os
print(os.getcwd())

C:\Users\Subhashini
